/**
 * ProcBoss (pboss) — build the runtime-agnostic dist bundle.
 *
 * Produces the files the PUBLISHED package ships so the same CLI runs under
 * Bun, Node and Deno:
 *
 *   dist/cli.js          — the CLI entry (node shebang; ESM). Any runtime
 *                          executes it; the runtime adapter layer picks the
 *                          native APIs of whichever runtime is running it.
 *   dist/api.mjs         — the library entry (import { PBoss } from "pboss").
 *   dist/postinstall.js  — the npm postinstall hook (plain JS; runs under
 *                          whichever package manager executes it).
 *
 * The bundle contains all three adapters; each adapter module has zero
 * top-level side effects, so loading the file never touches another
 * runtime's globals — only the executing runtime's implementation runs.
 *
 * https://procboss.com
 * License: GPL-3.0-only
 */

import { spawnSync } from "node:child_process";
import { mkdirSync, readFileSync, writeFileSync, chmodSync, existsSync, rmSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = dirname(dirname(fileURLToPath(import.meta.url)));

mkdirSync(join(ROOT, "dist"), { recursive: true });

const NODE_SHEBANG = "#!/usr/bin/env node\n";

/** Run a command at the repo root, inheriting stdio. */
function run(cmd: string[]) {
  const r = spawnSync(cmd[0]!, cmd.slice(1), { cwd: ROOT, stdio: "inherit" });
  if (r.status !== 0) {
    console.error(`✗ build step failed: ${cmd.join(" ")}`);
    process.exit(1);
  }
}

/** Prepend a shebang to an output file and mark it executable. */
function addShebang(rel: string) {
  const abs = join(ROOT, rel);
  const body = readFileSync(abs, "utf8");
  if (!body.startsWith("#!")) {
    writeFileSync(abs, NODE_SHEBANG + body);
  }
  chmodSync(abs, 0o755);
}

// 1. The CLI — target node so node: builtins resolve; Bun.* / Deno.* stay
//    as globals the adapter branches reach only under their own runtime.
console.log("Building dist/cli.js …");
run(["bun", "build", "--target=node", "--format=esm", `--outfile=${join(ROOT, "dist/cli.js")}`, "./src/main.ts"]);
addShebang("dist/cli.js");

// 2. The library entry — same treatment, .mjs for unambiguous ESM.
console.log("Building dist/api.mjs …");
run(["bun", "build", "--target=node", "--format=esm", `--outfile=${join(ROOT, "dist/api.mjs")}`, "./src/api.ts"]);

// 3. The postinstall hook — built from the source that guards on
//    import.meta.main; the built file IS the entry, so run it unconditionally
//    via a tiny wrapper.
console.log("Building dist/postinstall.js …");
const wrapper = join(ROOT, "scripts", ".postinstall-entry.ts");
writeFileSync(
  wrapper,
  [
    '// generated by build-dist.ts — the postinstall bundle is an entry,',
    '// so it runs unconditionally (the source file keeps its dev-mode guard).',
    'import { runPostinstall } from "../src/postinstall";',
    'await runPostinstall();',
    "",
  ].join("\n")
);
try {
  run(["bun", "build", "--target=node", "--format=esm", wrapper, `--outfile=${join(ROOT, "dist/postinstall.js")}`]);
} finally {
  rmSync(wrapper, { force: true });
}
addShebang("dist/postinstall.js");

// Sanity: the three outputs exist and are non-empty.
for (const f of ["dist/cli.js", "dist/api.mjs", "dist/postinstall.js"]) {
  const abs = join(ROOT, f);
  if (!existsSync(abs) || readFileSync(abs, "utf8").length < 1000) {
    console.error(`✗ ${f} missing or suspiciously small`);
    process.exit(1);
  }
  console.log(`✓ ${f}`);
}
console.log("dist build complete — runs under Bun, Node and Deno.");
