/**
 * ProcBoss (pboss) — the node:cluster primary wrapper.
 *
 * Owner rule (2026-09-29): when an app's runtime is Node and it runs in
 * cluster mode / with instances > 1, the workers MUST be forked through
 * Node's own cluster API — it is the only clustering a Node script can use,
 * and the only one that shares the listening port across workers (the
 * primary distributes connections on every platform — no SO_REUSEPORT, no
 * macOS/Windows limitation). The runtime pboss itself runs under (Bun, Deno,
 * Node) is irrelevant to that requirement: the CLUSTERING is delegated to a
 * dedicated Node primary process, and pboss supervises that one process.
 *
 * pboss spawns this wrapper as the app's single OS process and hands it the
 * job through env vars (PBOSS_TARGET_SCRIPT / PBOSS_TARGET_ARGS /
 * PBOSS_CLUSTER_INSTANCES / PBOSS_BASE_PORT / PBOSS_KILL_TIMEOUT). The
 * wrapper:
 *
 *   - forks the N workers with cluster.fork(), each with the standard pboss
 *     identity env (PBOSS_WORKER_ID / PBOSS_INSTANCES / NODE_APP_INSTANCE,
 *     BM2_* aliases) and the SHARED base port (node:cluster does the
 *     sharing — the +workerId port offset belongs to the process-based
 *     instance model, not this one);
 *   - respawns a crashed worker with backoff (fast crashes double the delay,
 *     capped at 15s; a worker that lived 30s resets it) — the app stays up,
 *     and pboss's own restart policy still guards the wrapper;
 *   - reloads with ZERO DOWNTIME on SIGHUP — a replacement worker is forked
 *     and confirmed online BEFORE the old one is retired, one at a time;
 *   - tears every worker down on SIGTERM/SIGINT (disconnect, then a hard
 *     kill capped by the app's kill timeout).
 *
 * The wrapper runs under the same Node (and node flags) the workers get:
 * cluster workers inherit the primary's execArgv, so type stripping or a
 * `--import tsx` loader propagate from the wrapper command to every worker.
 *
 * The file is GENERATED at first use into PBOSS_HOME and rewritten whenever
 * the embedded source changes — nothing to package, nothing to version, and
 * a `pboss upgrade` refreshes it on the next spawn automatically.
 *
 * https://procboss.com
 * License: GPL-3.0-only
 */

import { join } from "path";
import { readFile, writeFile, mkdir } from "fs/promises";
import { PBOSS_HOME } from "./constants.ts";

/** The generated wrapper's file name inside PBOSS_HOME. */
export const NODE_CLUSTER_WRAPPER_NAME = "node-cluster-wrapper.mjs";

/**
 * The wrapper's full source. Plain ESM JavaScript that runs on any Node the
 * app itself runs on (cluster.setupPrimary: Node ≥ 16). Written as a
 * non-template string on purpose so the wrapper can freely use its own
 * template literals.
 */
export const NODE_CLUSTER_WRAPPER_SOURCE = [
  "#!/usr/bin/env node",
  "/**",
  " * ProcBoss (pboss) — node:cluster primary wrapper. GENERATED by pboss;",
  " * do not edit — pboss rewrites this file whenever its embedded source",
  " * changes (see src/node-cluster.ts in the pboss repo).",
  " */",
  'import cluster from "node:cluster";',
  "",
  "const env = process.env;",
  'const SCRIPT = env.PBOSS_TARGET_SCRIPT || "";',
  'const APP_ARGS = JSON.parse(env.PBOSS_TARGET_ARGS || "[]");',
  'const TOTAL = Math.max(1, parseInt(env.PBOSS_CLUSTER_INSTANCES || "1", 10) || 1);',
  "const BASE_PORT = env.PBOSS_BASE_PORT ? parseInt(env.PBOSS_BASE_PORT, 10) : null;",
  'const KILL_TIMEOUT = Math.max(0, parseInt(env.PBOSS_KILL_TIMEOUT || "5000", 10));',
  "const RELOAD_ONLINE_TIMEOUT = 10000; // cap per replacement worker during a rolling reload",
  "const RESPAWN_BASE_DELAY = 300;",
  "const RESPAWN_MAX_DELAY = 15000;",
  "const STABLE_UPTIME_MS = 30000; // a worker that lived this long resets its backoff",
  "",
  "if (!SCRIPT) {",
  '  console.error("[pboss-cluster] PBOSS_TARGET_SCRIPT is missing - refusing to start");',
  "  process.exit(1);",
  "}",
  "",
  "cluster.setupPrimary({ exec: SCRIPT, args: APP_ARGS, windowsHide: true });",
  "",
  "// cluster worker.id -> the app worker index (PBOSS_WORKER_ID / NODE_APP_INSTANCE)",
  "const appIndex = new Map();",
  "const forkedAt = new Map();",
  "const crashes = new Map();",
  "",
  "function workerEnv(i) {",
  "  return {",
  '    PBOSS_CLUSTER: "true",',
  '    PBOSS_WORKER_ID: String(i),',
  '    PBOSS_INSTANCES: String(TOTAL),',
  '    BM2_CLUSTER: "true",',
  '    BM2_WORKER_ID: String(i),',
  '    BM2_INSTANCES: String(TOTAL),',
  '    NODE_APP_INSTANCE: String(i),',
  "    // node:cluster SHARES the base port across workers - that is the",
  "    // point of clustering a Node app. The +workerId port offset belongs to",
  "    // pboss's process-based instance model, not to this one.",
  "    ...(BASE_PORT !== null ? { PORT: String(BASE_PORT) } : {}),",
  "  };",
  "}",
  "",
  "// EVERY forked worker pid, kept by the wrapper itself. node:cluster can",
  "// mark a disconnected worker dead internally (isDead() true, 'exit' fired)",
  "// while the OS process still runs - so teardown never trusts cluster",
  "// state and SIGKILLs the recorded pids directly. A pid leaves this set",
  "// only when kill(pid, 0) proves the process is gone.",
  "const workerPids = new Set();",
  "",
  "function pidDead(pid) {",
  "  try { process.kill(pid, 0); return false; }",
  '  catch (err) { return !err || err.code === "ESRCH"; }',
  "}",
  "",
  "function killWorkersHard() {",
  "  for (const w of Object.values(cluster.workers)) {",
  "    if (w && w.process) {",
  '      try { w.process.kill("SIGKILL"); } catch { /* already dead - ESRCH is fine here */ }',
  "    }",
  "  }",
  "    for (const pid of workerPids) {",
  '      try { process.kill(pid, "SIGKILL"); } catch { /* already dead - ESRCH is fine here */ }',
  "    }",
  "}",
  "",
  "function forkWorker(i) {",
  "  const w = cluster.fork(workerEnv(i));",
  "  appIndex.set(w.id, i);",
  "  forkedAt.set(w.id, Date.now());",
  "  if (w.process && w.process.pid) workerPids.add(w.process.pid);",
  "  return w;",
  "}",
  "",
  "let stopping = false;",
  "let reloading = false;",
  "",
  "for (let i = 0; i < TOTAL; i++) forkWorker(i);",
  "",
  "cluster.on(\"exit\", (worker, code, signal) => {",
  "  const i = appIndex.get(worker.id);",
  "  const livedMs = forkedAt.has(worker.id) ? Date.now() - forkedAt.get(worker.id) : 0;",
  "  const pid = worker.process ? worker.process.pid : undefined;",
  "  appIndex.delete(worker.id);",
  "  forkedAt.delete(worker.id);",
  "  // Forget the pid only when the process is PROVEN gone - the exit event",
  "  // can fire while a disconnected worker still runs.",
  "  if (pid !== undefined && pidDead(pid)) workerPids.delete(pid);",
  "  if (stopping) {",
  "    if (appIndex.size === 0) { killWorkersHard(); process.exit(0); }",
  "    return;",
  "  }",
  "  // backoff: fast crashes double the respawn delay (capped); a worker",
  "  // that lived a stable run resets its counter.",
  "  const prev = crashes.get(i) || 0;",
  "  const next = livedMs >= STABLE_UPTIME_MS ? 0 : prev + 1;",
  "  crashes.set(i, next);",
  "  const delay = Math.min(RESPAWN_MAX_DELAY, RESPAWN_BASE_DELAY * Math.pow(2, next - 1));",
  "  console.error(",
  '    "[pboss-cluster] worker " + i + " exited (code=" + code + " signal=" + signal + ")",',
  '    "- respawning in " + delay + "ms"',
  "  );",
  "  // Respawn only when the pid is REALLY gone - the exit event can fire",
  "  // while the process still runs (a rolling reload retires that one",
  "  // itself); forking a replacement then would over-subscribe the app.",
  "  const respawn = setTimeout(() => {",
  "    if (stopping) return;",
  "    if (pid !== undefined && !pidDead(pid)) return;",
  "    forkWorker(i);",
  "  }, Math.max(delay, 250));",
  "  if (respawn.unref) respawn.unref();",
  "});",
  "",
  "function shutdown(signal) {",
  "  if (stopping) return;",
  "  stopping = true;",
  '  console.error("[pboss-cluster] " + signal + " received - stopping " + appIndex.size + " worker(s)");',
  "  // Graceful: disconnect lets each worker close its servers (the",
  "  // node:cluster handshake). A worker whose channel is already closing",
  "  // emits EPIPE on the Worker object — an async 'error' event, NOT a",
  "  // throw — so each Worker gets a no-op error listener first: the",
  "  // wrapper must never crash out of its own teardown path. The hard",
  "  // stages below (SIGTERM, then SIGKILL) cap the wait at the app's",
  "  // configured kill timeout.",
  "  for (const w of Object.values(cluster.workers)) {",
  "    if (!w || w.isDead()) continue;",
  '    w.once("error", () => {}); // an EPIPE while the channel closes is expected',
  "    try { w.disconnect(); } catch {",
  "      // the channel may already be closing - the hard stages below still reap the worker",
  "    }",
  "  }",
  "  const finish = () => {",
  "    killWorkersHard();",
  "    process.exit(0);",
  "  };",
  "  const term = setTimeout(() => {",
  "    for (const pid of workerPids) {",
  '      try { process.kill(pid, "SIGTERM"); } catch { /* already dead - ESRCH is fine here */ }',
  "    }",
  "  }, KILL_TIMEOUT);",
  "  const hard = setTimeout(finish, KILL_TIMEOUT + 2000);",
  "  if (term.unref) term.unref();",
  "  if (hard.unref) hard.unref();",
  "  // the exit handler above exits when the last worker is gone",
  "}",
  "",
  'process.on("SIGTERM", () => shutdown("SIGTERM"));',
  'process.on("SIGINT", () => shutdown("SIGINT"));',
  "",
  "const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms));",
  "",
  "// Zero-downtime rolling reload: for each OLD worker, fork its replacement",
  "// (same app index, so identities are stable across generations), wait for",
  "// it to come online, and only then retire the old one.",
  'process.on("SIGHUP", async () => {',
  "  if (stopping || reloading) return;",
  "  reloading = true;",
  "  try {",
  "    const olds = Object.values(cluster.workers).filter((w) => w && !w.isDead());",
  '    console.error("[pboss-cluster] SIGHUP - zero-downtime rolling reload (" + olds.length + " worker(s))");',
  "    for (const old of olds) {",
  "      if (stopping) return; // a stop arrived mid-reload — abandon the roll",
  "      const i = appIndex.get(old.id);",
  "      const next = forkWorker(i);",
  "      await new Promise((resolve) => {",
  "        const t = setTimeout(resolve, RELOAD_ONLINE_TIMEOUT);",
  "        if (t.unref) t.unref();",
  '        next.once("online", () => { clearTimeout(t); resolve(); });',
  "      });",
  "      if (stopping) return;",
  "      // EPIPE while the old worker's channel closes must not crash the",
  "      // wrapper (same lesson as shutdown): no-op error listener first.",
  '      old.once("error", () => {});',
  "      try { old.disconnect(); } catch {",
  "        // the old worker may already be closing - the retire timer below still reaps it",
  "      }",
  "      const retirePid = old.process ? old.process.pid : undefined;",
  "      const retire = setTimeout(() => {",
  "        if (retirePid !== undefined) {",
  '          try { process.kill(retirePid, "SIGTERM"); } catch { /* already dead - ESRCH is fine here */ }',
  "        }",
  "      }, 2000);",
  "      if (retire.unref) retire.unref();",
  "      await sleep(150); // tiny stagger so replacements never all land at once",
  "    }",
  '    console.error("[pboss-cluster] rolling reload complete");',
  "  } finally {",
  "    reloading = false;",
  "  }",
  "});",
].join("\n") + "\n";

/**
 * Materialize the wrapper on disk (PBOSS_HOME/node-cluster-wrapper.mjs),
 * creating the directory when needed, and return its absolute path. The
 * content is compared first: an up-to-date file is left untouched (the
 * daemon may call this on every restart), and a stale one — from an older
 * pboss — is rewritten in place so `pboss upgrade` refreshes it on the next
 * spawn without any cleanup step.
 */
export async function ensureNodeClusterWrapper(): Promise<string> {
  const file = join(PBOSS_HOME, NODE_CLUSTER_WRAPPER_NAME);
  let existing: string | null = null;
  try {
    existing = await readFile(file, "utf8");
  } catch {
    // absent (first use, or a wiped PBOSS_HOME) — written below
  }
  if (existing !== NODE_CLUSTER_WRAPPER_SOURCE) {
    await mkdir(PBOSS_HOME, { recursive: true });
    await writeFile(file, NODE_CLUSTER_WRAPPER_SOURCE, "utf8");
  }
  return file;
}
