/**
 * ProcBoss (pboss) — the SO_REUSEPORT cluster shim (Deno and Bun apps).
 *
 * The cluster contract (owner report 2026-10-08: `pboss start --instances 3
 * ./server.ts` under Deno crash-looped — server-0 bound the port, server-1/2
 * died with AddrInUse, restart-looping forever): with instances > 1, N
 * workers must serve ONE shared port on every runtime.
 *
 *   Node apps — node:cluster: ONE wrapper primary forks the workers and
 *              distributes connections in-process (src/node-cluster.ts;
 *              the runtime's own clustering, works for any app shape).
 *
 *   Deno/Bun — SO_REUSEPORT: neither runtime has an in-process cluster API
 *              for its NATIVE servers (Deno.serve / Bun.serve), but both
 *              accept `reusePort: true`, and on Linux the kernel then lets
 *              N independent processes bind the SAME port and spreads
 *              connections across them (hash-based, since 3.9). pboss
 *              preloads this shim into every worker, and the shim patches
 *              the runtime's server APIs so the APP NEVER CHANGES —
 *              `Deno.serve({ port: 8000 }, handler)` shares 8000 across
 *              all workers exactly like a node:cluster app would.
 *
 * The preload rides the runtimes' own flags — deno: `--preload=<shim>` (+
 * `--unstable-net`: reusePort is a gated API there), bun: `--preload <shim>`
 * — inserted before the app script in buildWorkerCommand. The user's script
 * stays the MAIN module (import.meta.main, argv, cwd semantics untouched).
 *
 * Verified empirically (2026-10-08, deno 2.9.7 / bun 1.3.14 on Linux): three
 * preloaded processes, one port, requests served by all three (kernel
 * spread). Apps using node:http under deno/bun do NOT share through this
 * shim — they should pin `--interpreter node` (node:cluster) or manage
 * their own sharing; see DOCS.md.
 *
 * The shim file is GENERATED into PBOSS_HOME at first use and rewritten
 * whenever the embedded source changes — the same freshness contract as the
 * node:cluster wrapper (a `pboss upgrade` refreshes it on the next spawn).
 *
 * https://procboss.com
 * License: GPL-3.0-only
 */

import { join } from "path";
import { readFile, writeFile, mkdir } from "fs/promises";
import { PBOSS_HOME } from "./constants.ts";
import { getRuntime } from "./runtime/index.ts";

const R = getRuntime();

/** The generated shim's file name inside PBOSS_HOME. */
export const REUSEPORT_SHIM_NAME = "reuseport-shim.mjs";

/** The generated capability probe's file name inside PBOSS_HOME. */
export const REUSEPORT_PROBE_NAME = "reuseport-probe.mjs";

/**
 * The shim's full source. Plain ES JavaScript (no syntax a 2020 runtime
 * cannot parse — it preloads into the USER's runtime, which pboss does not
 * control) that patches the native server APIs of whichever runtime loads
 * it. Written as a non-template string on purpose so the shim can freely
 * use its own template literals.
 */
export const REUSEPORT_SHIM_SOURCE = [
  "/**",
  " * ProcBoss (pboss) — SO_REUSEPORT cluster shim. GENERATED by pboss;",
  " * do not edit — pboss rewrites this file whenever its embedded source",
  " * changes (see src/reuseport-cluster.ts in the pboss repo).",
  " *",
  " * Loaded via --preload into every CLUSTER worker (instances > 1) of a",
  " * Deno or Bun app: patches Deno.serve / Deno.listen / Bun.serve to set",
  " * reusePort: true on every TCP bind, so N workers share one port and",
  " * the kernel spreads the connections. Single-instance apps never load",
  " * this file; an app that states its own reusePort keeps it.",
  " */",
  "(function () {",
  "  \"use strict\";",
  "",
  "  // Only patch when the option is missing and the port is a real,",
  "  // user-chosen port: port 0 asks the kernel for a random port — sharing",
  "  // a RANDOM port is meaningless (each worker would get its own).",
  "  function wantsReuse(o) {",
  "    return o && typeof o === \"object\" &&",
  "      typeof o.port === \"number\" && o.port > 0 &&",
  "      !(\"reusePort\" in o);",
  "  }",
  "  function setReuse(o) {",
  "    try {",
  "      Object.defineProperty(o, \"reusePort\", { value: true, enumerable: true });",
  "    } catch (e) {",
  "      try { o.reusePort = true; } catch (e2) { /* frozen options — leave it */ }",
  "    }",
  "  }",
  "",
  "  // ── Deno ─────────────────────────────────────────────────────────",
  "  if (typeof globalThis.Deno === \"object\" && globalThis.Deno !== null) {",
  "    var D = globalThis.Deno;",
  "    if (typeof D.serve === \"function\") {",
  "      var origServe = D.serve;",
  "      D.serve = function (a, b) {",
  "        var aObj = a && typeof a === \"object\" ? a : null;",
  "        var bObj = b && typeof b === \"object\" ? b : null;",
  "        // serve(options, handler) / serve(options with fetch)",
  "        if (wantsReuse(aObj)) setReuse(aObj);",
  "        // serve(handler, options)",
  "        else if (wantsReuse(bObj)) setReuse(bObj);",
  "        // serve(handler) — no options at all: rebuild as options so the",
  "        // DEFAULT port (8000) shares too. {fetch: handler} is the same",
  "        // call the runtime itself makes for the one-argument form.",
  "        else if (typeof a === \"function\" && b === undefined) {",
  "          return origServe({ fetch: a, reusePort: true });",
  "        }",
  "        return origServe(a, b);",
  "      };",
  "    }",
  "    if (typeof D.listen === \"function\") {",
  "      var origListen = D.listen;",
  "      D.listen = function (o) {",
  "        if (wantsReuse(o) && (o.transport === undefined || o.transport === \"tcp\")) {",
  "          return origListen(Object.assign({}, o, { reusePort: true }));",
  "        }",
  "        return origListen(o);",
  "      };",
  "    }",
  "  }",
  "",
  "  // ── Bun ──────────────────────────────────────────────────────────",
  "  if (typeof globalThis.Bun === \"object\" && globalThis.Bun !== null) {",
  "    var B = globalThis.Bun;",
  "    if (typeof B.serve === \"function\") {",
  "      var origBunServe = B.serve;",
  "      B.serve = function (o) {",
  "        if (wantsReuse(o)) {",
  "          return origBunServe(Object.assign({}, o, { reusePort: true }));",
  "        }",
  "        return origBunServe(o);",
  "      };",
  "    }",
  "  }",
  "})();",
].join("\n") + "\n";

/**
 * The capability probe's full source. A cluster spawn must never guess: the
 * flags pboss adds (deno's --unstable-net, both runtimes' --preload) and the
 * reusePort option itself only exist on some runtime versions, and a worker
 * that dies on an unknown flag is a crash-loop. The probe does the one
 * thing that PROVES sharing — binds the same port TWICE, explicitly with
 * reusePort — under the exact spawn shape the workers get (shim preloaded).
 * It runs once per runtime binary per daemon lifetime, then the verdict is
 * cached.
 */
export const REUSEPORT_PROBE_SOURCE = [
  "/** ProcBoss (pboss) — SO_REUSEPORT capability probe. GENERATED; do not edit. */",
  "(async function () {",
  "  // A pid-derived port: unique per probe run, outside the ephemeral",
  "  // range, vanishingly unlikely to collide with a real listener.",
  "  var port = 20000 + (process.pid % 20000);",
  "  function ok() { console.log(\"REUSEPORT_OK\"); process.exit(0); }",
  "  function fail(err) {",
  "    console.error(String((err && err.message) || err));",
  "    process.exit(1);",
  "  }",
  "  try {",
  "    if (typeof globalThis.Deno === \"object\" && globalThis.Deno !== null) {",
  "      var a = Deno.serve({ port: port, reusePort: true }, function () { return new Response(\"a\"); });",
  "      // The second bind is the verdict: without working reusePort this",
  "      // throws AddrInUse and the probe (and thus the cluster shim) is",
  "      // honestly unsupported on this runtime.",
  "      var b = Deno.serve({ port: port, reusePort: true }, function () { return new Response(\"b\"); });",
  "      await new Promise(function (r) { setTimeout(r, 150); });",
  "      await a.shutdown();",
  "      await b.shutdown();",
  "      ok();",
  "    } else if (typeof globalThis.Bun === \"object\" && globalThis.Bun !== null) {",
  "      var s1 = Bun.serve({ port: port, reusePort: true, fetch: function () { return new Response(\"a\"); } });",
  "      var s2 = Bun.serve({ port: port, reusePort: true, fetch: function () { return new Response(\"b\"); } });",
  "      await new Promise(function (r) { setTimeout(r, 100); });",
  "      s1.stop(true);",
  "      s2.stop(true);",
  "      ok();",
  "    } else {",
  "      fail(new Error(\"neither Deno nor Bun\"));",
  "    }",
  "  } catch (err) {",
  "    fail(err);",
  "  }",
  "})();",
].join("\n") + "\n";

/**
 * Materialize the shim (and its probe) on disk in PBOSS_HOME, creating the
 * directory when needed, and return both absolute paths. Same freshness
 * contract as the node:cluster wrapper: an up-to-date file is left
 * untouched, a stale one — from an older pboss — is rewritten in place so
 * `pboss upgrade` refreshes it on the next spawn without a cleanup step.
 */
export async function ensureReusePortFiles(): Promise<{ shim: string; probe: string }> {
  const shim = join(PBOSS_HOME, REUSEPORT_SHIM_NAME);
  const probe = join(PBOSS_HOME, REUSEPORT_PROBE_NAME);
  for (const [file, source] of [
    [shim, REUSEPORT_SHIM_SOURCE],
    [probe, REUSEPORT_PROBE_SOURCE],
  ] as const) {
    let existing: string | null = null;
    try {
      existing = await readFile(file, "utf8");
    } catch {
      // absent (first use, or a wiped PBOSS_HOME) — written below
    }
    if (existing !== source) {
      await mkdir(PBOSS_HOME, { recursive: true });
      await writeFile(file, source, "utf8");
    }
  }
  return { shim, probe };
}

/**
 * Whether this platform has the kernel feature the shim depends on.
 * SO_REUSEPORT with TCP load-balancing is a Linux guarantee (≥ 3.9); the
 * runtimes themselves document reusePort as Linux-supported. Other
 * platforms keep the process-based per-instance model (PORT offsets) —
 * enabling an unverified kernel semantic there would trade a crash-loop for
 * a silent single-worker serving, which is worse than the honest offset
 * behavior.
 */
export function reusePortClusterPlatform(platform: NodeJS.Platform): boolean {
  return platform === "linux";
}

/** The probe verdict cache: one per runtime binary per daemon lifetime. */
const probeVerdicts = new Map<string, Promise<boolean>>();

/**
 * Can this runtime binary actually run the cluster shape? Runs the probe —
 * `deno run --unstable-net --preload=<shim> <probe>` (bun: `bun run
 * --preload <shim> <probe>`) — once, cached by binary path. A runtime that
 * lacks the flags or the reusePort option answers false and the cluster
 * falls back to today's per-instance model (no crash-loop on an unknown
 * flag). The spawn shape the probe uses is EXACTLY the workers' shape, so
 * the verdict covers flags, preload and kernel sharing in one run.
 */
export function runtimeSupportsReusePort(
  bin: string,
  kind: "deno" | "bun",
): Promise<boolean> {
  const key = `${kind}:${bin}`;
  let verdict = probeVerdicts.get(key);
  if (!verdict) {
    verdict = (async () => {
      try {
        const { shim, probe } = await ensureReusePortFiles();
        // -A: the probe is pboss's OWN throwaway verification process, never
        // the user's app — it binds sockets to prove the FLAGS and the
        // kernel sharing, and its permission grant is deliberately decoupled
        // from the app's list (the workers' route is deny-by-default since
        // 2026-10-08; a zero-permission app still needs this verdict).
        const cmd =
          kind === "deno"
            ? [bin, "run", "-A", "--unstable-net", `--preload=${shim}`, probe]
            : [bin, "run", "--preload", shim, probe];
        // Bounded: a pathological hang must not stall a start forever.
        // The loser of the race is simply "unsupported" (the safe
        // fallback); the probe itself dies with the daemon eventually.
        const timer = new Promise<boolean>((resolve) => {
          const t = setTimeout(() => resolve(false), 15_000);
          if (typeof (t as unknown as { unref?: () => void }).unref === "function") {
            (t as unknown as { unref: () => void }).unref();
          }
        });
        const run = (async () => {
          const { exitCode } = await R.process.capture(cmd);
          return exitCode === 0;
        })();
        return await Promise.race([run, timer]);
      } catch {
        return false;
      }
    })();
    probeVerdicts.set(key, verdict);
  }
  return verdict;
}
